"""add user vault sharetoken models

Revision ID: de26d69b69c6
Revises: 
Create Date: 2026-03-29 19:35:45.520396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de26d69b69c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('preview_file_path', sa.String(length=512), nullable=True),
    sa.Column('parent_document_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('forgery_result', sa.JSON(), nullable=False),
    sa.Column('qr_result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_parent_document_id'), ['parent_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('vault_items',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('encrypted_key', sa.String(length=512), nullable=False),
    sa.Column('minio_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_items_user_id'), ['user_id'], unique=False)

    op.create_table('share_tokens',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('vault_item_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_item_id'], ['vault_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_share_tokens_vault_item_id'), ['vault_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_tokens_vault_item_id'))
        batch_op.drop_index(batch_op.f('ix_share_tokens_token'))

    op.drop_table('share_tokens')
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_vault_items_document_id'))

    op.drop_table('vault_items')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_parent_document_id'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
